style.fill: transparent

vars: {
  d2-config: {
    pad: 8
    center: true
    theme-id: 0
  }
}

classes: {
  node: {
    style: {
      fill: "#f1f1f1"
      stroke: "#4c566a"
      font-color: "#212121"
      font: mono
      stroke-width: 1
      border-radius: 0
      shadow: false
    }
  }
  accent: {
    style: {
      fill: "#f1f1f1"
      stroke: "#005f87"
      font-color: "#000000"
      font: mono
      stroke-width: 2
      border-radius: 0
    }
  }
  ok: {
    style: {
      fill: "#f1f1f1"
      stroke: "#0b6e4f"
      font-color: "#000000"
      font: mono
      stroke-width: 2
      border-radius: 0
    }
  }
  edge: {
    style: {
      stroke: "#005f87"
      font-color: "#005f87"
      font: mono
      stroke-width: 2
    }
  }
}
